### ISSUE TITLE
Darius  Ult

### ISSUE THREAD

**Issue by SamuelLachance** [RyTak/LeaguePlusPlus#2]
Why you predict the castposition for darius ult ? , it's a targeting spell 
Darius.cpp in Killsteal function : 
`		
if (KSR->Enabled() && R->IsReady())
				{
					auto dmg = GHealthPrediction->GetKSDamage(Enemy, kSlotR, R->GetDelay(), true);
					Vec3 pos;
					int hit;
					GPrediction->FindBestCastPosition(R->Range(), R->Radius(), true, true, false, pos, hit);
					if (Enemy->GetHealth() <= dmg)
					{
						R->CastOnPosition(pos);
					}
				}`

**Comment by RyTak** [comment]
That's part of my template I used. It's not in my supported list until all of the spell behaviors are correct.
